# Spring db properties
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: CONECTA_SALUD
      username: develop
      password: develop
  
# HTTP Server
server:
  port: 8081
  servlet:
     contextPath: /clinica